name: APP_WMS

on:
  push:
    branches: [ "main" ]

jobs:
  build-and-push:
    runs-on: self-hosted
    environment: Giropops

    steps:
      - name: Baixar c√≥digo (Checkout)
        uses: actions/checkout@v4

      - name: Setup Docker Buildx
        uses: docker/setup-buildx-action@v3

      # Loga no seu Registry Privado na AWS
      - name: Login no Registry Privado
        uses: docker/login-action@v3
        with:
          registry: ${{ secrets.REGISTRY_URL }}
          username: ${{ secrets.REGISTRY_USER }}
          password: ${{ secrets.REGISTRY_PASS }}

      # Cria a imagem e envia para a AWS
      - name: Build and Push
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: ${{ secrets.REGISTRY_URL }}/giropops-html:latest
