name: APP_Giropops

on:
  push:
    # ðŸ‘‡ Agora ele escuta tanto a main quanto a develop
    branches: [ "main", "dev" ]

jobs:
  build-and-push:
    runs-on: self-hosted
    environment: Giropops

    steps:
      - name: Baixar cÃ³digo (Checkout)
        uses: actions/checkout@v4

      - name: Setup Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Definir Tags (Metadados)
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ secrets.REGISTRY_URL }}/giropops-html
          tags: |
            # Se for main, cria a tag 'latest'
            type=raw,value=latest,enable=${{ github.ref == 'refs/heads/main' }}
            # Se for develop, cria a tag 'staging'
            type=raw,value=staging,enable=${{ github.ref == 'refs/heads/dev' }}

      - name: Login no Registry Privado
        uses: docker/login-action@v3
        with:
          registry: ${{ secrets.REGISTRY_URL }}
          username: ${{ secrets.REGISTRY_USER }}
          password: ${{ secrets.REGISTRY_PASS }}

      - name: Build and Push
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: ${{ steps.meta.outputs.tags }}
